CREATE DATABASE IF NOT EXISTS govjob_portal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE govjob_portal;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100),
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) UNIQUE NOT NULL,
  password VARCHAR(255),
  role ENUM('STUDENT','TEACHER','HR','ADMIN') NOT NULL DEFAULT 'STUDENT',
  state VARCHAR(100),
  city VARCHAR(100),
  profilePicture VARCHAR(255),
  isVerified BOOLEAN DEFAULT FALSE,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE jobs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  department VARCHAR(255),
  description LONGTEXT NOT NULL,
  sector VARCHAR(100) NOT NULL,
  jobCategory VARCHAR(100),
  state VARCHAR(100),
  city VARCHAR(100),
  salary VARCHAR(100),
  applicationFee DECIMAL(10,2) DEFAULT 0,
  totalPositions INT DEFAULT 1,
  qualifications VARCHAR(255),
  eligibility TEXT,
  minAge INT,
  maxAge INT,
  examStartDate DATETIME,
  examEndDate DATETIME,
  applicationDeadline DATETIME,
  resultDate DATETIME,
  minSkillMarks DECIMAL(5,2) DEFAULT 0,
  createdBy INT,
  status ENUM('OPEN','CLOSED','CANCELLED') DEFAULT 'OPEN',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (createdBy) REFERENCES users(id)
);

CREATE TABLE applications (
  id INT PRIMARY KEY AUTO_INCREMENT,
  jobId INT NOT NULL,
  userId INT NOT NULL,
  applicationFeeAmount DECIMAL(10,2),
  feeStatus ENUM('PENDING','PAID','FAILED') DEFAULT 'PENDING',
  skillTestScore DECIMAL(5,2),
  applicationStatus ENUM('PENDING','SELECTED','REJECTED','WITHDRAWN') DEFAULT 'PENDING',
  appliedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (jobId) REFERENCES jobs(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_application (jobId, userId)
);

CREATE TABLE exams (
  id INT PRIMARY KEY AUTO_INCREMENT,
  jobId INT NOT NULL,
  examName VARCHAR(255) NOT NULL,
  examDate DATETIME,
  admitCardReleaseDate DATETIME,
  resultDate DATETIME,
  centerCity VARCHAR(100),
  FOREIGN KEY (jobId) REFERENCES jobs(id) ON DELETE CASCADE
);

CREATE TABLE results (
  id INT PRIMARY KEY AUTO_INCREMENT,
  jobId INT NOT NULL,
  userId INT NOT NULL,
  rank INT,
  scoreObtained DECIMAL(5,2),
  totalScore DECIMAL(5,2),
  percentage DECIMAL(5,2),
  selectedStatus ENUM('SELECTED','WAITING','NOT_SELECTED'),
  documentVerificationStatus ENUM('PENDING','APPROVED','REJECTED') DEFAULT 'PENDING',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (jobId) REFERENCES jobs(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE skill_tests (
  id INT PRIMARY KEY AUTO_INCREMENT,
  jobId INT,
  title VARCHAR(255) NOT NULL,
  description LONGTEXT,
  totalQuestions INT DEFAULT 100,
  timeLimit INT DEFAULT 120,
  passingMarks DECIMAL(5,2) DEFAULT 40,
  totalMarks DECIMAL(5,2) DEFAULT 100,
  isActive BOOLEAN DEFAULT TRUE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (jobId) REFERENCES jobs(id) ON DELETE SET NULL
);

CREATE TABLE questions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  testId INT NOT NULL,
  question LONGTEXT NOT NULL,
  optionA VARCHAR(255),
  optionB VARCHAR(255),
  optionC VARCHAR(255),
  optionD VARCHAR(255),
  correctAnswer CHAR(1),
  marks DECIMAL(3,1) DEFAULT 1,
  FOREIGN KEY (testId) REFERENCES skill_tests(id) ON DELETE CASCADE
);

CREATE TABLE chats (
  id INT PRIMARY KEY AUTO_INCREMENT,
  participantOneId INT NOT NULL,
  participantTwoId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (participantOneId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (participantTwoId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE messages (
  id INT PRIMARY KEY AUTO_INCREMENT,
  chatId INT,
  senderId INT NOT NULL,
  receiverId INT NOT NULL,
  message LONGTEXT NOT NULL,
  fileUrl VARCHAR(255),
  isRead BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chatId) REFERENCES chats(id) ON DELETE CASCADE,
  FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (receiverId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE hr_connections (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  hrId INT NOT NULL,
  status ENUM('PENDING','ACCEPTED','REJECTED','BLOCKED') DEFAULT 'PENDING',
  requestMessage LONGTEXT,
  requestedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  respondedAt DATETIME,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (hrId) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_connection (userId, hrId)
);

CREATE TABLE previous_papers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  jobId INT NOT NULL,
  paperName VARCHAR(255),
  examYear INT,
  fileUrl VARCHAR(255),
  uploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (jobId) REFERENCES jobs(id) ON DELETE CASCADE
);

CREATE TABLE notifications (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  type VARCHAR(50),
  title VARCHAR(255),
  message LONGTEXT,
  relatedId INT,
  isRead BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE resumes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  userId INT NOT NULL,
  headline VARCHAR(255),
  education LONGTEXT,
  skills LONGTEXT,
  experience LONGTEXT,
  fileUrl VARCHAR(255),
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);
